# Generated by Django 4.2.7 on 2025-08-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='location',
        ),
        migrations.AddField(
            model_name='footer',
            name='company_description',
            field=models.TextField(blank=True, help_text='Breve descripción de la empresa', verbose_name='Descripción de la empresa'),
        ),
        migrations.AddField(
            model_name='footer',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Dirección de correo electrónico', max_length=254, verbose_name='Email de la empresa'),
        ),
        migrations.AddField(
            model_name='footer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nombre completo de la empresa', max_length=200, verbose_name='Nombre de la empresa'),
        ),
        migrations.AddField(
            model_name='footer',
            name='company_phone',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono de la empresa'),
        ),
        migrations.AddField(
            model_name='footer',
            name='location_address',
            field=models.TextField(blank=True, help_text='Dirección física de la empresa', verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='footer',
            name='location_city',
            field=models.CharField(blank=True, help_text='Ciudad donde se encuentra la empresa', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='footer',
            name='location_country',
            field=models.CharField(blank=True, help_text='País donde se encuentra la empresa', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='sections',
            field=models.TextField(blank=True, help_text='Secciones del footer separadas por comas (ej: Productos, Servicios, Soporte)', verbose_name='Secciones del footer'),
        ),
    ]
