# Generated by Django 4.2.7 on 2025-08-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.CharField(max_length=50, verbose_name='Icono')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoría de Apoyo Comunitario',
                'verbose_name_plural': 'Categorías de Apoyo Comunitario',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='communitysupport',
            options={'verbose_name': 'Apoyo a la Comunidad', 'verbose_name_plural': 'Apoyo a la Comunidad'},
        ),
        migrations.RemoveField(
            model_name='communitysupport',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='communitysupport',
            name='initiatives',
        ),
        migrations.AlterField(
            model_name='communitysupport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='communitysupport',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='communitysupport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communitysupport',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='communitysupport',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='communitysupport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.CreateModel(
            name='CommunityInitiative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('impact', models.TextField(verbose_name='Impacto')),
                ('image_src', models.ImageField(blank=True, null=True, upload_to='community/initiatives/', verbose_name='Imagen')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto alternativo de imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='about.communitycategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Iniciativa de Apoyo Comunitario',
                'verbose_name_plural': 'Iniciativas de Apoyo Comunitario',
                'ordering': ['category', 'id'],
            },
        ),
    ]
