# Generated by Django 4.2.7 on 2025-08-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_financialdocument_financialstatement_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementsConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Estados Financieros', max_length=200, verbose_name='Título')),
                ('description', models.TextField(default='Consulta nuestros estados financieros auditados y trimestrales', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Estados Financieros',
                'verbose_name_plural': 'Configuración de Estados Financieros',
            },
        ),
        migrations.AlterModelOptions(
            name='financialdocument',
            options={'ordering': ['-year', 'document_type', 'quarter'], 'verbose_name': 'Documento Financiero', 'verbose_name_plural': 'Documentos Financieros'},
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='year',
            field=models.CharField(blank=True, help_text='Ej: 2024, 2023, 2022', max_length=4, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='document_type',
            field=models.CharField(choices=[('audited', 'Auditado'), ('quarterly', 'Trimestral')], max_length=10, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='quarter',
            field=models.CharField(blank=True, help_text='1, 2, 3, 4 (solo para documentos trimestrales)', max_length=2, null=True, verbose_name='Trimestre'),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL del documento'),
        ),
        migrations.AlterUniqueTogether(
            name='financialdocument',
            unique_together={('year', 'document_type', 'quarter')},
        ),
        migrations.DeleteModel(
            name='FinancialStatement',
        ),
    ]
