# Generated by Django 4.2.7 on 2025-08-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_change_url_to_file_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Memorias', max_length=200, verbose_name='Título')),
                ('description', models.TextField(default='Un recorrido por nuestra historia y logros institucionales', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Memorias',
                'verbose_name_plural': 'Configuración de Memorias',
            },
        ),
        migrations.CreateModel(
            name='MemoryDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('file', models.FileField(blank=True, help_text='Subir archivo PDF de la memoria anual', null=True, upload_to='memory_documents/', verbose_name='Archivo PDF')),
                ('year', models.CharField(help_text='Ej: 2023, 2022, 2021', max_length=4, verbose_name='Año')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Documento de Memoria',
                'verbose_name_plural': 'Documentos de Memoria',
                'ordering': ['-year'],
                'unique_together': {('year',)},
            },
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
