# Generated by Django 4.2.7 on 2025-08-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_memoryconfig_memorydocument_delete_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorydocument',
            name='title',
        ),
    ]
