# Generated by Django 4.2.7 on 2025-08-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_remove_memorydocument_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('icon', models.CharField(help_text='Nombre del icono (ej: shield, cog, check-circle)', max_length=50, verbose_name='Icono')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoría de Políticas',
                'verbose_name_plural': 'Categorías de Políticas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PolicyConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Políticas', max_length=200, verbose_name='Título')),
                ('description', models.TextField(default='Nuestras políticas institucionales garantizan la transparencia y eficiencia en nuestras operaciones.', verbose_name='Descripción')),
                ('download_text', models.CharField(default='Descargar documento', max_length=100, verbose_name='Texto de descarga')),
                ('last_update_text', models.CharField(default='Última actualización', max_length=100, verbose_name='Texto de última actualización')),
                ('all_policies_text', models.CharField(default='Todas las Políticas', max_length=100, verbose_name='Texto de todas las políticas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Políticas',
                'verbose_name_plural': 'Configuración de Políticas',
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('file', models.FileField(blank=True, help_text='Subir archivo PDF de la política', null=True, upload_to='policy_documents/', verbose_name='Archivo PDF')),
                ('last_update', models.DateField(help_text='Fecha de la última actualización del documento', verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Documento de Política',
                'verbose_name_plural': 'Documentos de Política',
                'ordering': ['-last_update'],
            },
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.AddField(
            model_name='policycategory',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='categories', to='about.policydocument', verbose_name='Documentos'),
        ),
    ]
