# Generated by Django 4.2.7 on 2025-08-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_policycategory_policyconfig_policydocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mision',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la misión', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='nuestrahistoria',
            name='paragraphs',
            field=models.TextField(blank=True, help_text='Párrafos separados por doble salto de línea (Enter)', verbose_name='Párrafos'),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='paragraphs',
            field=models.TextField(blank=True, help_text='Párrafos separados por doble salto de línea (Enter)', verbose_name='Párrafos'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la visión', verbose_name='Descripción'),
        ),
    ]
