# Generated by Django 4.2.7 on 2025-08-20 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.CharField(help_text='Identificador único del tipo de cuenta', max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Nombre descriptivo del tipo de cuenta', max_length=200, verbose_name='Etiqueta')),
                ('description', models.TextField(help_text='Descripción detallada del tipo de cuenta', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el tipo de cuenta está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta',
                'verbose_name_plural': 'Tipos de Cuenta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AbandonedAccountsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la sección de cuentas abandonadas', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción de la sección', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la sección está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_types', models.ManyToManyField(help_text='Tipos de cuenta disponibles en esta sección', to='prousuario.accounttype', verbose_name='Tipos de Cuenta')),
            ],
            options={
                'verbose_name': 'Sección de Cuentas Abandonadas',
                'verbose_name_plural': 'Secciones de Cuentas Abandonadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YearlyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Año del documento', max_length=4, verbose_name='Año')),
                ('title', models.CharField(help_text='Título del documento', max_length=200, verbose_name='Título')),
                ('document', models.FileField(help_text='Archivo PDF del documento', upload_to='documents/abandoned-accounts/', verbose_name='Documento')),
                ('date', models.DateField(help_text='Fecha del documento', verbose_name='Fecha')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el documento está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(help_text='Tipo de cuenta al que pertenece el documento', on_delete=django.db.models.deletion.CASCADE, to='prousuario.accounttype', verbose_name='Tipo de Cuenta')),
            ],
            options={
                'verbose_name': 'Documento Anual',
                'verbose_name_plural': 'Documentos Anuales',
                'ordering': ['-year', 'account_type'],
                'unique_together': {('year', 'account_type')},
            },
        ),
    ]
