# Generated by Django 4.2.7 on 2025-08-20 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0002_alter_accounttype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlydocument',
            name='type',
            field=models.CharField(choices=[('abandoned', 'Abandonadas'), ('inactive', 'Inactivas')], default='abandoned', help_text='Tipo de documento (abandoned o inactive)', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='yearlydocument',
            name='document',
            field=models.FileField(help_text='Archivo PDF del documento', max_length=255, upload_to='documents/abandoned-accounts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documento'),
        ),
    ]
