# Generated by Django 4.2.7 on 2025-08-21 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0003_yearlydocument_type_alter_yearlydocument_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountContractsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la sección de contratos', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción de la sección de contratos', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la sección está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección de Contratos de Adhesión',
                'verbose_name_plural': 'Secciones de Contratos de Adhesión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría de contratos', max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Contrato',
                'verbose_name_plural': 'Categorías de Contratos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del contrato', max_length=300, verbose_name='Título')),
                ('url', models.URLField(help_text='URL del archivo PDF del contrato', verbose_name='URL del documento')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición del contrato', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el contrato está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Categoría del contrato', on_delete=django.db.models.deletion.CASCADE, to='prousuario.contractcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
