# Generated by Django 4.2.7 on 2025-08-21 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0004_accountcontractssection_contractcategory_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='url',
        ),
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, help_text='Archivo PDF del contrato', max_length=255, null=True, upload_to='documents/contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documento'),
        ),
    ]
