# Generated by Django 4.2.7 on 2025-08-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0005_remove_contract_url_contract_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nombre completo del solicitante', max_length=200, verbose_name='Nombre completo')),
                ('document', models.CharField(help_text='Número de documento de identidad', max_length=20, verbose_name='Documento de identidad')),
                ('phone', models.CharField(help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Correo electrónico de contacto', max_length=254, verbose_name='Correo electrónico')),
                ('product_type', models.CharField(help_text='Tipo de producto relacionado con el reclamo', max_length=100, verbose_name='Tipo de producto')),
                ('claim_type', models.CharField(help_text='Tipo de reclamo o solicitud', max_length=100, verbose_name='Tipo de reclamo')),
                ('distribution_channel', models.CharField(help_text='Canal a través del cual se realizó la transacción', max_length=100, verbose_name='Canal de distribución')),
                ('message', models.TextField(help_text='Descripción detallada del reclamo o solicitud', verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado'), ('rejected', 'Rechazado')], default='pending', help_text='Estado actual del reclamo', max_length=20, verbose_name='Estado')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas internas para el seguimiento del reclamo', null=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Fecha cuando se resolvió el reclamo', null=True, verbose_name='Fecha de resolución')),
            ],
            options={
                'verbose_name': 'Solicitud de Reclamo',
                'verbose_name_plural': 'Solicitudes de Reclamos',
                'ordering': ['-created_at'],
            },
        ),
    ]
