# Generated by Django 4.2.7 on 2025-08-22 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0006_claimrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nombre completo del denunciante', max_length=200, verbose_name='Nombre completo')),
                ('document', models.CharField(help_text='Número de documento de identidad', max_length=20, verbose_name='Documento de identidad')),
                ('phone', models.CharField(help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Correo electrónico de contacto', max_length=254, verbose_name='Correo electrónico')),
                ('classification', models.CharField(help_text='Tipo de fraude reportado', max_length=100, verbose_name='Clasificación del fraude')),
                ('message', models.TextField(help_text='Descripción detallada del fraude reportado', verbose_name='Descripción del fraude')),
                ('file', models.FileField(blank=True, help_text='Archivo de evidencia (PDF, imagen, etc.)', max_length=255, null=True, upload_to='fraud_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='Archivo adjunto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado'), ('rejected', 'Rechazado')], default='pending', help_text='Estado actual del reporte', max_length=20, verbose_name='Estado')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas internas para el seguimiento del reporte', null=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Fecha cuando se resolvió el reporte', null=True, verbose_name='Fecha de resolución')),
            ],
            options={
                'verbose_name': 'Reporte de Fraude',
                'verbose_name_plural': 'Reportes de Fraude',
                'ordering': ['-created_at'],
            },
        ),
    ]
