# Generated by Django 4.2.7 on 2025-08-22 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0007_fraudreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsAndDutiesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(help_text='Título principal de la página de derechos y deberes', max_length=200, verbose_name='Título de la Página')),
                ('page_description', models.TextField(help_text='Descripción general de la página de derechos y deberes', verbose_name='Descripción de la Página')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la página está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de Derechos y Deberes',
                'verbose_name_plural': 'Páginas de Derechos y Deberes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RightsAndDutiesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(choices=[('rightsAndDuties', 'Derechos y Deberes'), ('otherRights', 'Otros Derechos')], help_text='Identificador único de la sección', max_length=50, verbose_name='ID de Sección')),
                ('title', models.CharField(help_text='Título de la sección', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción de la sección', verbose_name='Descripción')),
                ('button_text', models.CharField(help_text='Texto que aparecerá en el botón de la sección', max_length=100, verbose_name='Texto del Botón')),
                ('additional_info', models.TextField(blank=True, help_text='Información adicional de la sección (opcional)', null=True, verbose_name='Información Adicional')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición de la sección', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la sección está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(help_text='Página a la que pertenece esta sección', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='prousuario.rightsanddutiespage', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Sección de Derechos y Deberes',
                'verbose_name_plural': 'Secciones de Derechos y Deberes',
                'ordering': ['order', 'title'],
                'unique_together': {('page', 'section_id')},
            },
        ),
        migrations.CreateModel(
            name='RightsAndDutiesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen de la sección', upload_to='user-support/rights/', verbose_name='Imagen')),
                ('alt_text', models.CharField(help_text='Texto alternativo para la imagen', max_length=200, verbose_name='Texto Alternativo')),
                ('description', models.CharField(help_text='Descripción de la imagen', max_length=300, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición de la imagen', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la imagen está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(help_text='Sección a la que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='prousuario.rightsanddutiessection', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Imagen de Derechos y Deberes',
                'verbose_name_plural': 'Imágenes de Derechos y Deberes',
                'ordering': ['section', 'order', 'alt_text'],
            },
        ),
    ]
