# Generated by Django 4.2.7 on 2025-08-22 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0008_rightsanddutiespage_rightsanddutiessection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría de servicios', max_length=100, verbose_name='Nombre')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición de la categoría', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicios',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['order', 'name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='ServiceRatesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la página de tarifas', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción general de las tarifas de servicios', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la página está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de Tarifas de Servicios',
                'verbose_name_plural': 'Páginas de Tarifas de Servicios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rightsanddutiessection',
            unique_together={('section_id',)},
        ),
        migrations.RemoveField(
            model_name='rightsanddutiessection',
            name='page',
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='Nombre del servicio', max_length=200, verbose_name='Servicio')),
                ('description', models.TextField(help_text='Descripción detallada del servicio', verbose_name='Descripción')),
                ('rate', models.CharField(help_text='Precio o tarifa del servicio (ej: RD$ 500.00, Gratis, 6%)', max_length=100, verbose_name='Tarifa')),
                ('details', models.JSONField(blank=True, default=list, help_text='Lista de detalles adicionales del servicio', verbose_name='Detalles')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición del servicio', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la tarifa está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Categoría a la que pertenece esta tarifa', on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='prousuario.servicecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Tarifa de Servicio',
                'verbose_name_plural': 'Tarifas de Servicios',
                'ordering': ['category', 'order', 'service'],
                'unique_together': {('category', 'service')},
            },
        ),
    ]
