# Generated by Django 4.2.7 on 2025-08-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0009_servicecategory_serviceratespage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='details',
            field=models.TextField(help_text='Detalles adicionales del servicio con formato rico', verbose_name='Detalles'),
        ),
    ]
