# Generated by Django 4.2.7 on 2025-08-22 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0010_alter_servicerate_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la provincia', max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la provincia está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nombre completo del solicitante', max_length=200, verbose_name='Nombre completo')),
                ('document', models.CharField(help_text='Número de documento de identidad', max_length=20, verbose_name='Documento de identidad')),
                ('phone', models.CharField(help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Correo electrónico de contacto', max_length=254, verbose_name='Correo electrónico')),
                ('classification', models.CharField(help_text='Tipo de sugerencia o comentario', max_length=100, verbose_name='Clasificación')),
                ('message', models.TextField(help_text='Descripción detallada de la sugerencia o comentario', verbose_name='Sugerencia')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado'), ('rejected', 'Rechazado')], default='pending', help_text='Estado actual de la sugerencia', max_length=20, verbose_name='Estado')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas internas para el seguimiento de la sugerencia', null=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Fecha cuando se procesó la sugerencia', null=True, verbose_name='Fecha de resolución')),
                ('province', models.ForeignKey(help_text='Provincia de residencia', on_delete=django.db.models.deletion.CASCADE, to='prousuario.province', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Buzón de Sugerencias',
                'verbose_name_plural': 'Buzón de Sugerencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
