# Generated by Django 4.2.7 on 2025-08-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_buy_rate', models.BooleanField(default=True, help_text='Indica si se debe mostrar la tasa de compra', verbose_name='Mostrar tasa de compra')),
                ('show_sell_rate', models.BooleanField(default=False, help_text='Indica si se debe mostrar la tasa de venta', verbose_name='Mostrar tasa de venta')),
                ('currency_name', models.CharField(default='US DOLAR', help_text='Nombre de la moneda (ej: US DOLAR, EURO)', max_length=50, verbose_name='Nombre de la moneda')),
                ('buy_rate', models.DecimalField(decimal_places=4, default=55.5, help_text='Tasa de compra de la moneda', max_digits=10, verbose_name='Tasa de compra')),
                ('sell_rate', models.DecimalField(decimal_places=4, default=56.5, help_text='Tasa de venta de la moneda', max_digits=10, verbose_name='Tasa de venta')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la tasa de cambio está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_type', models.CharField(choices=[('individual', 'Individual'), ('empresarial', 'Empresarial')], max_length=20)),
                ('menu_items', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navigation',
                'verbose_name_plural': 'Navigations',
                'ordering': ['navigation_type'],
            },
        ),
    ]
