# Generated by Django 4.2.7 on 2025-08-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='menu_items',
            field=models.TextField(blank=True, help_text='Elementos del menú separados por comas (ej: Inicio, Productos, Servicios, Contacto)', verbose_name='Elementos del menú'),
        ),
    ]
