# Generated by Django 4.2.7 on 2025-08-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.AddField(
            model_name='account',
            name='account_image',
            field=models.ImageField(blank=True, help_text='Imagen principal de la cuenta', null=True, upload_to='products/accounts/', verbose_name='Imagen de la cuenta'),
        ),
        migrations.AddField(
            model_name='account',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Imagen de banner para la cuenta', null=True, upload_to='products/accounts/banners/', verbose_name='Imagen de banner'),
        ),
        migrations.AddField(
            model_name='account',
            name='benefits',
            field=models.TextField(blank=True, help_text='Beneficios de la cuenta con formato enriquecido', verbose_name='Beneficios'),
        ),
        migrations.AddField(
            model_name='account',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requisitos para abrir la cuenta separados por comas', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('savings', 'Cuenta de Ahorros'), ('checking', 'Cuenta Corriente'), ('business', 'Cuenta Empresarial'), ('student', 'Cuenta Estudiantil'), ('classic_physical', 'Cuenta Física Clásica')], help_text='Categoría de la cuenta', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(help_text='Descripción breve de la cuenta', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='account',
            name='features',
            field=models.TextField(blank=True, help_text='Características del producto separadas por comas', verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta está activa', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(help_text='Título de la cuenta', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='card',
            name='features',
            field=models.TextField(blank=True, help_text='Características de la tarjeta separadas por comas', verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='rates',
            field=models.TextField(blank=True, help_text='Tasas de interés separadas por comas', verbose_name='Tasas'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Préstamo Personal'), ('business', 'Préstamo Empresarial'), ('mortgage', 'Préstamo Hipotecario'), ('vehicle', 'Préstamo Vehicular'), ('student', 'Préstamo Estudiantil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requisitos del préstamo separados por comas', verbose_name='Requisitos'),
        ),
    ]
