# Generated by Django 4.2.7 on 2025-08-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_account_image_account_account_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='benefits',
        ),
        migrations.CreateModel(
            name='AccountBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('FaMoneyBillWave', '💰 Dinero/Efectivo'), ('FaCreditCard', '💳 Tarjeta de Crédito'), ('FaChartLine', '📈 Gráficos/Inversiones'), ('FaMobileAlt', '📱 Móvil/Banca Móvil'), ('FaHome', '🏠 Casa/Hipoteca'), ('FaCar', '🚗 Auto/Vehicular'), ('FaGraduationCap', '🎓 Estudios/Educación'), ('FaBuilding', '🏢 Empresa/Negocio'), ('FaShieldAlt', '🛡️ Seguridad/Protección'), ('FaGift', '🎁 Beneficios/Regalos'), ('FaStar', '⭐ Calidad/Excelencia'), ('FaHeart', '❤️ Amor/Preferencia'), ('FaUsers', '👥 Comunidad/Personas'), ('FaHandshake', '🤝 Acuerdos/Servicios'), ('FaLightbulb', '💡 Ideas/Innovación'), ('FaRocket', '🚀 Crecimiento/Progreso'), ('FaGem', '💎 Valor/Premium'), ('FaCrown', '👑 Liderazgo/Excelencia'), ('FaTrophy', '🏆 Logros/Éxito'), ('FaMedal', '🥇 Reconocimiento/Calidad')], help_text='Icono de FontAwesome para el beneficio', max_length=50, verbose_name='Icono')),
                ('text', models.TextField(help_text='Descripción del beneficio', verbose_name='Texto del beneficio')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_benefits', to='products.account')),
            ],
            options={
                'verbose_name': 'Beneficio de Cuenta',
                'verbose_name_plural': 'Beneficios de Cuenta',
                'ordering': ['id'],
            },
        ),
    ]
