# Generated by Django 4.2.7 on 2025-08-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_account_benefits_accountbenefit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_type', 'title'], 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.AddField(
            model_name='card',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Imagen de banner para la tarjeta', null=True, upload_to='products/cards/banners/', verbose_name='Imagen de banner'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Imagen principal de la tarjeta', null=True, upload_to='products/cards/', verbose_name='Imagen de la tarjeta'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('debit', 'Tarjeta de Débito'), ('credit', 'Tarjeta de Crédito'), ('prepaid', 'Tarjeta Prepago'), ('business', 'Tarjeta Empresarial'), ('student', 'Tarjeta Estudiantil')], default='debit', help_text='Tipo de tarjeta', max_length=20, verbose_name='Tipo de tarjeta'),
        ),
        migrations.AddField(
            model_name='card',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requisitos para obtener la tarjeta separados por comas', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(help_text='Descripción breve de la tarjeta', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la tarjeta está activa', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(help_text='Título de la tarjeta', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.CreateModel(
            name='CardBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('FaMoneyBillWave', '💰 Dinero/Efectivo'), ('FaCreditCard', '💳 Tarjeta de Crédito'), ('FaChartLine', '📈 Gráficos/Inversiones'), ('FaMobileAlt', '📱 Móvil/Banca Móvil'), ('FaHome', '🏠 Casa/Hipoteca'), ('FaCar', '🚗 Auto/Vehicular'), ('FaGraduationCap', '🎓 Estudios/Educación'), ('FaBuilding', '🏢 Empresa/Negocio'), ('FaShieldAlt', '🛡️ Seguridad/Protección'), ('FaGift', '🎁 Beneficios/Regalos'), ('FaStar', '⭐ Calidad/Excelencia'), ('FaHeart', '❤️ Amor/Preferencia'), ('FaUsers', '👥 Comunidad/Personas'), ('FaHandshake', '🤝 Acuerdos/Servicios'), ('FaLightbulb', '💡 Ideas/Innovación'), ('FaRocket', '🚀 Crecimiento/Progreso'), ('FaGem', '💎 Valor/Premium'), ('FaCrown', '👑 Liderazgo/Excelencia'), ('FaTrophy', '🏆 Logros/Éxito'), ('FaMedal', '🥇 Reconocimiento/Calidad'), ('FaGlobeAmericas', '🌎 Aceptación Global')], help_text='Icono de FontAwesome para el beneficio', max_length=50, verbose_name='Icono')),
                ('text', models.TextField(help_text='Descripción del beneficio', verbose_name='Texto del beneficio')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_benefits', to='products.card')),
            ],
            options={
                'verbose_name': 'Beneficio de Tarjeta',
                'verbose_name_plural': 'Beneficios de Tarjeta',
                'ordering': ['id'],
            },
        ),
    ]
