# Generated by Django 4.2.7 on 2025-08-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_card_options_remove_card_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['certificate_type', 'title'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='rates',
        ),
        migrations.AddField(
            model_name='certificate',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Imagen de banner para el certificado', null=True, upload_to='products/certificates/banners/', verbose_name='Imagen de banner'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='benefits_title',
            field=models.CharField(default='Beneficios de tu Certificado Financiero', help_text='Título de la sección de beneficios', max_length=200, verbose_name='Título de beneficios'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(blank=True, help_text='Imagen principal del certificado', null=True, upload_to='products/certificates/', verbose_name='Imagen del certificado'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('financial', 'Certificado Financiero'), ('investment', 'Certificado de Inversión'), ('savings', 'Certificado de Ahorro'), ('business', 'Certificado Empresarial')], default='financial', help_text='Tipo de certificado', max_length=20, verbose_name='Tipo de certificado'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cta_apply',
            field=models.CharField(default='Solicitar', help_text='Texto del botón de solicitar', max_length=50, verbose_name='Texto del botón solicitar'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cta_rates',
            field=models.CharField(default='Tarifario', help_text='Texto del botón de tarifario', max_length=50, verbose_name='Texto del botón tarifario'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='deposit_rates_title',
            field=models.CharField(default='Escala de Tasas de Captaciones de Depósitos', help_text='Título de la sección de tasas de depósito', max_length=200, verbose_name='Título de tasas de depósito'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='deposit_rates_valid_from',
            field=models.CharField(default='Vigente desde el 31 de enero del 2023', help_text='Texto de vigencia de las tasas', max_length=200, verbose_name='Vigencia de tasas'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='faq_title',
            field=models.CharField(default='Preguntas Frecuentes Certificado Financiero', help_text='Título de la sección de preguntas frecuentes', max_length=200, verbose_name='Título de FAQ'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='investment_details',
            field=models.TextField(blank=True, help_text='Detalles de la inversión separados por comas', verbose_name='Detalles de inversión'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='investment_subtitle',
            field=models.CharField(default='Especificaciones del depósito a plazo fijo para personas:', help_text='Subtítulo de la sección de inversión', max_length=200, verbose_name='Subtítulo de inversión'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='investment_title',
            field=models.CharField(default='Tu nueva Inversión', help_text='Título de la sección de inversión', max_length=200, verbose_name='Título de inversión'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='rates_title',
            field=models.CharField(default='Tarifas', help_text='Título de la sección de tarifas', max_length=200, verbose_name='Título de tarifas'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='requirements',
            field=models.TextField(blank=True, help_text='Requisitos separados por comas', verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='requirements_title',
            field=models.CharField(default='Requisitos', help_text='Título de la sección de requisitos', max_length=200, verbose_name='Título de requisitos'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtítulo del certificado', max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(help_text='Descripción del certificado', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el certificado está activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(help_text='Título principal del certificado', max_length=200, verbose_name='Título principal'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.CreateModel(
            name='CertificateRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Etiqueta de la tarifa (ej: Monto de apertura)', max_length=200, verbose_name='Etiqueta')),
                ('value', models.CharField(help_text='Valor de la tarifa (ej: $5,000,000.00)', max_length=100, verbose_name='Valor')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_rates', to='products.certificate')),
            ],
            options={
                'verbose_name': 'Tarifa de Certificado',
                'verbose_name_plural': 'Tarifas de Certificado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CertificateFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Pregunta frecuente', verbose_name='Pregunta')),
                ('answer', models.TextField(help_text='Respuesta a la pregunta frecuente', verbose_name='Respuesta')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_faqs', to='products.certificate')),
            ],
            options={
                'verbose_name': 'FAQ de Certificado',
                'verbose_name_plural': 'FAQs de Certificado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CertificateDepositRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(help_text='Rango de monto (ej: De 10,000.00 a 500,000.00)', max_length=200, verbose_name='Rango')),
                ('rate', models.CharField(help_text='Tasa de interés (ej: 5%)', max_length=50, verbose_name='Tasa')),
                ('term', models.CharField(help_text='Plazo de la inversión (ej: de 30 a 90 días)', max_length=100, verbose_name='Plazo')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_deposit_rates', to='products.certificate')),
            ],
            options={
                'verbose_name': 'Tasa de Depósito de Certificado',
                'verbose_name_plural': 'Tasas de Depósito de Certificado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CertificateBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del beneficio del certificado', max_length=200, verbose_name='Título del beneficio')),
                ('description', models.TextField(help_text='Descripción detallada del beneficio', verbose_name='Descripción del beneficio')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_benefits', to='products.certificate')),
            ],
            options={
                'verbose_name': 'Beneficio de Certificado',
                'verbose_name_plural': 'Beneficios de Certificado',
                'ordering': ['id'],
            },
        ),
    ]
