# Generated by Django 4.2.7 on 2025-08-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_certificate_options_remove_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['loan_type', 'title'], 'verbose_name': 'Préstamo Hipotecario', 'verbose_name_plural': 'Préstamos Hipotecarios'},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='image',
        ),
        migrations.AddField(
            model_name='loan',
            name='details',
            field=models.TextField(default='', help_text='Detalles del préstamo separados por comas', verbose_name='Detalles'),
        ),
        migrations.AddField(
            model_name='loan',
            name='requirements_title',
            field=models.CharField(default='Requisitos para Crédito Hipotecario', help_text='Título de la sección de requisitos', max_length=200, verbose_name='Título de requisitos'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='description',
            field=models.TextField(help_text='Descripción detallada del préstamo', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('home_purchase', 'Compra de vivienda'), ('remodelation', 'Ampliación o remodelación'), ('construction', 'Construcción'), ('land_purchase', 'Compra de terreno')], default='home_purchase', max_length=20, verbose_name='Tipo de préstamo'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='requirements',
            field=models.TextField(help_text='Requisitos del préstamo separados por comas', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='title',
            field=models.CharField(help_text='Título del préstamo hipotecario', max_length=200, verbose_name='Título'),
        ),
    ]
