# Generated by Django 4.2.7 on 2025-08-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_loan_options_remove_loan_image_loan_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('home_purchase', 'Compra de vivienda'), ('remodelation', 'Ampliación o remodelación'), ('construction', 'Contrucción'), ('land_purchase', 'Compra de terreno'), ('consumer', 'Préstamo de Consumo')], default='home_purchase', max_length=20, verbose_name='Tipo de préstamo'),
        ),
    ]
