# Generated by Django 4.2.7 on 2025-08-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCardPromo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título principal de la promoción', max_length=200, verbose_name='Título')),
                ('highlighted_title', models.CharField(help_text='Parte del título que se destaca visualmente', max_length=200, verbose_name='Título destacado')),
                ('description', models.TextField(help_text='Descripción detallada de la promoción', verbose_name='Descripción')),
                ('primary_button_text', models.CharField(help_text='Texto del botón de acción principal', max_length=100, verbose_name='Texto del botón principal')),
                ('secondary_button_text', models.CharField(help_text='Texto del botón de acción secundaria', max_length=100, verbose_name='Texto del botón secundario')),
                ('image', models.ImageField(blank=True, help_text='Imagen de la promoción de tarjeta de débito', null=True, upload_to='home/debit_card_promo/', verbose_name='Imagen')),
                ('image_alt', models.CharField(help_text='Descripción de la imagen para accesibilidad', max_length=200, verbose_name='Texto alternativo de la imagen')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la promoción está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Promoción de Tarjeta de Débito',
                'verbose_name_plural': 'Promociones de Tarjeta de Débito',
                'ordering': ['-created_at'],
            },
        ),
    ]
