# Generated by Django 4.2.7 on 2025-08-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Imagen del elemento educativo', upload_to='home/education/', verbose_name='Imagen')),
                ('alt', models.CharField(help_text='Descripción de la imagen para accesibilidad', max_length=200, verbose_name='Texto alternativo')),
                ('description', models.TextField(help_text='Descripción del elemento educativo', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el elemento está activo', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición del elemento', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Elemento Educativo',
                'verbose_name_plural': 'Elementos Educativos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título principal de la sección de educación', max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(help_text='Subtítulo descriptivo de la sección', max_length=300, verbose_name='Subtítulo')),
                ('footer_text', models.TextField(help_text='Texto que aparece al final de la sección', verbose_name='Texto del pie de página')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la sección está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('education_items', models.ManyToManyField(blank=True, related_name='sections', to='home.educationitem', verbose_name='Elementos educativos')),
            ],
            options={
                'verbose_name': 'Sección de Educación',
                'verbose_name_plural': 'Secciones de Educación',
                'ordering': ['-created_at'],
            },
        ),
    ]
