# Generated by Django 4.2.7 on 2025-08-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_educationitem_educationsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeKeAccountSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título principal del resumen de cuenta PeKe', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción del resumen de cuenta PeKe', verbose_name='Descripción')),
                ('button_text', models.CharField(help_text='Texto del botón de acción', max_length=100, verbose_name='Texto del botón')),
                ('image', models.ImageField(blank=True, help_text='Imagen del resumen de cuenta PeKe', null=True, upload_to='home/peke_account_summary/', verbose_name='Imagen')),
                ('image_alt', models.CharField(help_text='Descripción de la imagen para accesibilidad', max_length=200, verbose_name='Texto alternativo de la imagen')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el resumen está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Resumen de Cuenta PeKe',
                'verbose_name_plural': 'Resúmenes de Cuenta PeKe',
                'ordering': ['-created_at'],
            },
        ),
    ]
