# Generated by Django 4.2.7 on 2025-08-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pekeaccountsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título del producto', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción del producto', verbose_name='Descripción')),
                ('image', models.ImageField(help_text='Imagen del producto', upload_to='home/products/', verbose_name='Imagen')),
                ('category', models.CharField(choices=[('prestamos', 'Préstamos'), ('cuentas', 'Cuentas'), ('tarjetas', 'Tarjetas'), ('certificados', 'Certificados')], help_text='Categoría del producto', max_length=20, verbose_name='Categoría')),
                ('image_width', models.PositiveIntegerField(default=600, help_text='Ancho de la imagen en píxeles', verbose_name='Ancho de imagen')),
                ('image_height', models.PositiveIntegerField(default=400, help_text='Alto de la imagen en píxeles', verbose_name='Alto de imagen')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el producto está activo', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición del producto', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título principal de la sección de productos', max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(help_text='Subtítulo descriptivo de la sección', max_length=300, verbose_name='Subtítulo')),
                ('button_text', models.CharField(help_text='Texto del botón de acción', max_length=100, verbose_name='Texto del botón')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la sección está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('products', models.ManyToManyField(blank=True, related_name='sections', to='home.product', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Sección de Productos',
                'verbose_name_plural': 'Secciones de Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
