# Generated by Django 4.2.7 on 2025-08-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_productsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_desktop', models.ImageField(help_text='Imagen para dispositivos desktop (1920px width)', upload_to='home/slider/desktop/', verbose_name='Imagen Desktop')),
                ('image_tablet', models.ImageField(help_text='Imagen para dispositivos tablet (1024px width)', upload_to='home/slider/tablet/', verbose_name='Imagen Tablet')),
                ('image_mobile', models.ImageField(help_text='Imagen para dispositivos móviles (640px width)', upload_to='home/slider/mobile/', verbose_name='Imagen Mobile')),
                ('alt', models.CharField(help_text='Descripción de la imagen para accesibilidad', max_length=200, verbose_name='Texto alternativo')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el elemento del slider está activo', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el slider', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Elemento del Slider',
                'verbose_name_plural': 'Elementos del Slider',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
