# Generated by Django 4.2.7 on 2025-08-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de esta configuración', max_length=100, verbose_name='Nombre de la configuración')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Office 365'), ('yahoo', 'Yahoo'), ('custom', 'Servidor Personalizado')], help_text='Proveedor de email a utilizar', max_length=20, verbose_name='Proveedor de email')),
                ('host', models.CharField(help_text='Servidor SMTP (ej: smtp.gmail.com)', max_length=200, verbose_name='Servidor SMTP')),
                ('port', models.IntegerField(default=587, help_text='Puerto del servidor SMTP', verbose_name='Puerto')),
                ('use_tls', models.BooleanField(default=True, help_text='Habilitar cifrado TLS', verbose_name='Usar TLS')),
                ('username', models.CharField(help_text='Dirección de email o usuario', max_length=200, verbose_name='Usuario')),
                ('password', models.CharField(help_text='Contraseña o contraseña de aplicación', max_length=200, verbose_name='Contraseña')),
                ('from_email', models.CharField(help_text='Email que aparecerá como remitente', max_length=200, verbose_name='Email remitente')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta configuración está activa', verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, help_text='Usar esta configuración como predeterminada', verbose_name='Configuración por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuraciones de Email',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
    ]
