# Generated by Django 4.2.7 on 2025-08-21 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0006_claimrequest'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('claim_confirmation', 'Confirmación de Reclamo'), ('test', 'Email de Prueba'), ('system', 'Email del Sistema'), ('other', 'Otro')], help_text='Tipo de email enviado', max_length=50, verbose_name='Tipo de Email')),
                ('subject', models.CharField(help_text='Asunto del email', max_length=200, verbose_name='Asunto')),
                ('from_email', models.CharField(help_text='Email remitente', max_length=200, verbose_name='Remitente')),
                ('to_email', models.CharField(help_text='Email destinatario', max_length=200, verbose_name='Destinatario')),
                ('message', models.TextField(help_text='Contenido del email (texto plano)', verbose_name='Mensaje')),
                ('html_message', models.TextField(blank=True, help_text='Contenido HTML del email', null=True, verbose_name='Mensaje HTML')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido'), ('pending', 'Pendiente')], default='sent', help_text='Estado del envío', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, help_text='Error si el envío falló', null=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Real de Envío')),
                ('claim_request', models.ForeignKey(blank=True, help_text='Reclamo relacionado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prousuario.claimrequest', verbose_name='Solicitud de Reclamo')),
                ('email_config', models.ForeignKey(blank=True, help_text='Configuración usada para el envío', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailconfiguration', verbose_name='Configuración de Email')),
            ],
            options={
                'verbose_name': 'Registro de Email',
                'verbose_name_plural': 'Registros de Emails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_type', 'status'], name='core_emaill_email_t_aed125_idx'), models.Index(fields=['created_at'], name='core_emaill_created_be864d_idx'), models.Index(fields=['to_email'], name='core_emaill_to_emai_1de6bc_idx')],
            },
        ),
    ]
