# Generated by Django 4.2.7 on 2025-08-22 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prousuario', '0007_fraudreport'),
        ('core', '0002_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='fraud_report',
            field=models.ForeignKey(blank=True, help_text='Reporte de fraude relacionado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prousuario.fraudreport', verbose_name='Reporte de Fraude'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('claim_confirmation', 'Confirmación de Reclamo'), ('fraud_confirmation', 'Confirmación de Reporte de Fraude'), ('test', 'Email de Prueba'), ('system', 'Email del Sistema'), ('other', 'Otro')], help_text='Tipo de email enviado', max_length=50, verbose_name='Tipo de Email'),
        ),
    ]
