# Generated by Django 4.2.7 on 2025-08-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('branch', 'Sucursal'), ('atm', 'Cajero Automático')], help_text='Tipo de ubicación', max_length=10, verbose_name='Tipo')),
                ('name', models.CharField(help_text='Nombre de la ubicación', max_length=200, verbose_name='Nombre')),
                ('address', models.TextField(help_text='Dirección completa de la ubicación', verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True, verbose_name='Teléfono')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitud de la ubicación', max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitud de la ubicación', max_digits=11, verbose_name='Longitud')),
                ('opening_time', models.TimeField(blank=True, help_text='Hora de apertura (formato HH:MM)', null=True, verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(blank=True, help_text='Hora de cierre (formato HH:MM)', null=True, verbose_name='Hora de cierre')),
                ('is_open', models.BooleanField(default=True, help_text='Indica si la ubicación está abierta', verbose_name='Abierto')),
                ('services', models.JSONField(blank=True, default=list, help_text='Lista de servicios disponibles', verbose_name='Servicios')),
                ('schedule_text', models.CharField(blank=True, help_text='Texto descriptivo del horario', max_length=200, null=True, verbose_name='Texto de horario')),
                ('availability_class', models.CharField(blank=True, help_text='Clase CSS para indicar disponibilidad', max_length=50, null=True, verbose_name='Clase de disponibilidad')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la ubicación está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['type', 'name'],
            },
        ),
    ]
