# Generated by Django 4.2.7 on 2025-08-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:30 AM - 5:00 PM', '8:30 AM - 5:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('7:00 AM - 7:00 PM', '7:00 AM - 7:00 PM'), ('24/7', '24/7 - Siempre abierto'), ('6:00 AM - 10:00 PM', '6:00 AM - 10:00 PM'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('9:00 AM - 4:30 PM', '9:00 AM - 4:30 PM'), ('8:30 AM - 4:30 PM', '8:30 AM - 4:30 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('Lunes a Viernes 8:00 AM - 5:00 PM', 'Lunes a Viernes 8:00 AM - 5:00 PM'), ('Lunes a Viernes 9:00 AM - 6:00 PM', 'Lunes a Viernes 9:00 AM - 6:00 PM'), ('Lunes a Sábado 8:00 AM - 5:00 PM', 'Lunes a Sábado 8:00 AM - 5:00 PM'), ('Lunes a Sábado 9:00 AM - 6:00 PM', 'Lunes a Sábado 9:00 AM - 6:00 PM')], help_text='Selecciona el horario de la ubicación', max_length=100, verbose_name='Horario')),
                ('opening_time', models.TimeField(help_text='Hora de apertura (formato HH:MM)', verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(help_text='Hora de cierre (formato HH:MM)', verbose_name='Hora de cierre')),
                ('is_24_7', models.BooleanField(default=False, help_text='Indica si está abierto 24/7', verbose_name='24/7')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el horario está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='location',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='location',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Horario de la ubicación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.schedule', verbose_name='Horario'),
        ),
    ]
