# Generated by Django 4.2.7 on 2025-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_schedule_remove_location_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(choices=[('6:00 AM - 4:00 PM', '6:00 AM - 4:00 PM'), ('6:30 AM - 4:00 PM', '6:30 AM - 4:00 PM'), ('7:00 AM - 4:00 PM', '7:00 AM - 4:00 PM'), ('7:30 AM - 4:00 PM', '7:30 AM - 4:00 PM'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 4:30 PM', '8:00 AM - 4:30 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:30 AM - 4:00 PM', '8:30 AM - 4:00 PM'), ('8:30 AM - 4:30 PM', '8:30 AM - 4:30 PM'), ('8:30 AM - 5:00 PM', '8:30 AM - 5:00 PM'), ('8:30 AM - 5:30 PM', '8:30 AM - 5:30 PM'), ('9:00 AM - 4:00 PM', '9:00 AM - 4:00 PM'), ('9:00 AM - 4:30 PM', '9:00 AM - 4:30 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 5:30 PM', '9:00 AM - 5:30 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:30 AM - 5:00 PM', '9:30 AM - 5:00 PM'), ('9:30 AM - 5:30 PM', '9:30 AM - 5:30 PM'), ('9:30 AM - 6:00 PM', '9:30 AM - 6:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:30 AM - 6:00 PM', '8:30 AM - 6:00 PM'), ('8:30 AM - 6:30 PM', '8:30 AM - 6:30 PM'), ('9:00 AM - 6:30 PM', '9:00 AM - 6:30 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('5:00 AM - 3:00 PM', '5:00 AM - 3:00 PM'), ('5:30 AM - 3:00 PM', '5:30 AM - 3:00 PM'), ('5:30 AM - 3:30 PM', '5:30 AM - 3:30 PM'), ('6:00 AM - 3:00 PM', '6:00 AM - 3:00 PM'), ('6:00 AM - 3:30 PM', '6:00 AM - 3:30 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('10:00 AM - 6:30 PM', '10:00 AM - 6:30 PM'), ('10:00 AM - 7:00 PM', '10:00 AM - 7:00 PM'), ('10:30 AM - 6:00 PM', '10:30 AM - 6:00 PM'), ('10:30 AM - 6:30 PM', '10:30 AM - 6:30 PM'), ('10:30 AM - 7:00 PM', '10:30 AM - 7:00 PM'), ('11:00 AM - 7:00 PM', '11:00 AM - 7:00 PM'), ('11:00 AM - 8:00 PM', '11:00 AM - 8:00 PM'), ('12:00 PM - 8:00 PM', '12:00 PM - 8:00 PM'), ('1:00 PM - 9:00 PM', '1:00 PM - 9:00 PM'), ('2:00 PM - 10:00 PM', '2:00 PM - 10:00 PM'), ('6:00 AM - 10:00 PM', '6:00 AM - 10:00 PM'), ('7:00 AM - 10:00 PM', '7:00 AM - 10:00 PM'), ('7:00 AM - 11:00 PM', '7:00 AM - 11:00 PM'), ('8:00 AM - 10:00 PM', '8:00 AM - 10:00 PM'), ('8:00 AM - 11:00 PM', '8:00 AM - 11:00 PM'), ('24/7', '24/7 - Siempre abierto'), ('6:00 AM - 12:00 AM', '6:00 AM - 12:00 AM'), ('7:00 AM - 12:00 AM', '7:00 AM - 12:00 AM'), ('8:00 AM - 12:00 AM', '8:00 AM - 12:00 AM'), ('Lunes a Viernes 8:00 AM - 5:00 PM', 'Lunes a Viernes 8:00 AM - 5:00 PM'), ('Lunes a Viernes 8:30 AM - 5:00 PM', 'Lunes a Viernes 8:30 AM - 5:00 PM'), ('Lunes a Viernes 9:00 AM - 6:00 PM', 'Lunes a Viernes 9:00 AM - 6:00 PM'), ('Lunes a Viernes 9:00 AM - 5:30 PM', 'Lunes a Viernes 9:00 AM - 5:30 PM'), ('Lunes a Sábado 8:00 AM - 5:00 PM', 'Lunes a Sábado 8:00 AM - 5:00 PM'), ('Lunes a Sábado 8:30 AM - 5:00 PM', 'Lunes a Sábado 8:30 AM - 5:00 PM'), ('Lunes a Sábado 9:00 AM - 6:00 PM', 'Lunes a Sábado 9:00 AM - 6:00 PM'), ('Lunes a Sábado 9:00 AM - 5:30 PM', 'Lunes a Sábado 9:00 AM - 5:30 PM')], help_text='Selecciona el horario de la ubicación', max_length=100, verbose_name='Horario'),
        ),
    ]
