# Generated by Django 4.2.7 on 2025-08-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_schedule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='availability_class',
        ),
        migrations.RemoveField(
            model_name='location',
            name='schedule_text',
        ),
    ]
