# Generated by Django 4.2.7 on 2025-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_location_availability_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.TextField(help_text='Latitud de la ubicación', verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.TextField(help_text='Longitud de la ubicación', verbose_name='Longitud'),
        ),
    ]
