# Generated by Django 4.2.7 on 2025-08-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del servicio disponible', max_length=100, verbose_name='Nombre del servicio')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del servicio', null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el servicio está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='services',
        ),
        migrations.AddField(
            model_name='location',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Servicios disponibles en esta ubicación', to='locations.service', verbose_name='Servicios'),
        ),
    ]
