# Generated by Django 4.2.7 on 2025-08-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='slug',
        ),
    ]
