# Generated by Django 4.2.7 on 2025-08-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_slug_remove_promotion_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, help_text='Autor de la noticia', max_length=200, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, help_text='Categoría de la noticia', max_length=100, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_content',
            field=models.JSONField(blank=True, default=list, help_text='Contenido completo en formato estructurado', verbose_name='Contenido completo'),
        ),
        migrations.AddField(
            model_name='news',
            name='media',
            field=models.JSONField(blank=True, default=list, help_text='Galería de imágenes/videos adicionales', verbose_name='Media adicional'),
        ),
        migrations.AddField(
            model_name='news',
            name='related_links',
            field=models.JSONField(blank=True, default=list, help_text='Enlaces externos relacionados', verbose_name='Enlaces relacionados'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Lista de etiquetas relacionadas', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(help_text='Descripción breve de la noticia para listas/previews', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fecha_publicacion',
            field=models.DateTimeField(help_text='Fecha y hora de publicación', verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(help_text='Imagen principal de la noticia', upload_to='news/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la noticia está activa', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Título de la noticia', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(help_text='Descripción de la promoción', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='fecha_fin',
            field=models.DateField(help_text='Fecha de fin de la promoción', verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='fecha_inicio',
            field=models.DateField(help_text='Fecha de inicio de la promoción', verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen de la promoción', null=True, upload_to='promotions/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la promoción está activa', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(help_text='Título de la promoción', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
