# Generated by Django 4.2.7 on 2025-08-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options_alter_promotion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_content',
            field=models.TextField(blank=True, help_text='Contenido completo de la noticia con formato enriquecido', verbose_name='Contenido completo'),
        ),
    ]
