# Generated by Django 4.2.7 on 2025-08-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_full_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_content',
            field=models.TextField(help_text='Contenido completo de la noticia con formato enriquecido', verbose_name='Contenido completo'),
        ),
    ]
