# Generated by Django 4.2.7 on 2025-08-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_full_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='media',
        ),
        migrations.AddField(
            model_name='news',
            name='media_urls',
            field=models.TextField(blank=True, help_text='URLs de imágenes/videos separadas por comas', verbose_name='URLs de media adicional'),
        ),
        migrations.AlterField(
            model_name='news',
            name='related_links',
            field=models.TextField(blank=True, help_text='URLs de enlaces relacionados separadas por comas', verbose_name='Enlaces relacionados'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.TextField(blank=True, help_text='Etiquetas separadas por comas (ej: tecnología, finanzas, innovación)', verbose_name='Etiquetas'),
        ),
    ]
