# Generated by Django 4.2.7 on 2025-08-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_media_news_media_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='author',
            field=models.CharField(blank=True, help_text='Autor o departamento responsable', max_length=200, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='category',
            field=models.CharField(blank=True, help_text='Categoría de la promoción', max_length=100, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='full_content',
            field=models.TextField(blank=True, help_text='Contenido completo de la promoción con formato enriquecido', verbose_name='Contenido completo'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='media_urls',
            field=models.TextField(blank=True, help_text='URLs de imágenes/videos adicionales separadas por comas', verbose_name='URLs de media adicional'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='related_links',
            field=models.TextField(blank=True, help_text='URLs de enlaces relacionados separadas por comas', verbose_name='Enlaces relacionados'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='tags',
            field=models.TextField(blank=True, help_text='Etiquetas separadas por comas (ej: descuento, nuevo cliente, limitado)', verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='terms',
            field=models.TextField(blank=True, help_text='Términos y condiciones separados por comas', verbose_name='Términos y condiciones'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(help_text='Descripción breve de la promoción', verbose_name='Descripción'),
        ),
    ]
