# Generated by Django 4.2.7 on 2025-08-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_promotion_author_promotion_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='author',
        ),
    ]
