# Generated by Django 4.2.7 on 2025-08-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Pregunta frecuente', verbose_name='Pregunta')),
                ('answer', models.TextField(help_text='Respuesta a la pregunta frecuente', verbose_name='Respuesta')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición de la pregunta', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la pregunta está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SavingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del consejo de ahorro', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción breve del consejo', verbose_name='Descripción')),
                ('content', models.TextField(help_text='Contenido detallado del consejo', verbose_name='Contenido completo')),
                ('link', models.URLField(help_text='Enlace relacionado con el consejo', verbose_name='Enlace')),
                ('image', models.ImageField(blank=True, help_text='Imagen del consejo', null=True, upload_to='financial-guidance/tips/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición del consejo', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el consejo está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consejo de Ahorro',
                'verbose_name_plural': 'Consejos de Ahorro',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SliderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagen del slide', upload_to='financial-guidance/slider/', verbose_name='Imagen')),
                ('title', models.CharField(blank=True, help_text='Título del slide (opcional)', max_length=200, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción del slide (opcional)', null=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición del slide', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el slide está activo', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide del Slider',
                'verbose_name_plural': 'Slides del Slider',
                'ordering': ['order', 'id'],
            },
        ),
    ]
