# Generated by Django 4.2.7 on 2025-08-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacionfinanciera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingtip',
            name='image',
        ),
    ]
